export const ActionTypes = {
  FETCH_CURRENT_WEATHER_DEDAILS: "FETCH_CURRENT_WEATHER_DEDAILS",
  FETCH_LOCATION_WEATHER_DETAILS: "FETCH_LOCATION_WEATHER_DETAILS",
  FETCH_FORECAST_WEATHER_DETAILS: "FETCH_FORECAST_WEATHER_DETAILS",
  FETCH_CURRENT_FORECAST_WEATHER_DETAILS: "FETCH_CURRENT_FORECAST_WEATHER_DETAILS",
};
